"""preference_memory

Revision ID: 5e42162cea55
Revises: 96fccded09e3
Create Date: 2026-07-18 07:50:14.039771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42162cea55'
down_revision: Union[str, Sequence[str], None] = '96fccded09e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_key', sa.String(length=128), nullable=False),
    sa.Column('field_path', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_key', 'field_path', name='uq_pref_profile_path')
    )
    op.create_index(op.f('ix_preference_memory_profile_key'), 'preference_memory', ['profile_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_memory_profile_key'), table_name='preference_memory')
    op.drop_table('preference_memory')
    # ### end Alembic commands ###
