"""assumption_sets

Revision ID: 96fccded09e3
Revises: adbe8e6217a5
Create Date: 2026-07-18 07:26:33.475862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fccded09e3'
down_revision: Union[str, Sequence[str], None] = 'adbe8e6217a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumption_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_slug', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('schema_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_slug', 'version', name='uq_assumptions_project_version')
    )
    op.create_index(op.f('ix_assumption_sets_project_slug'), 'assumption_sets', ['project_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assumption_sets_project_slug'), table_name='assumption_sets')
    op.drop_table('assumption_sets')
    # ### end Alembic commands ###
